services:

  # --- PHP (Le Cerveau) ---
  php:
    build: docker/php
    volumes:
      - .:/var/www:delegated # Partage du code source
    depends_on:
      - database


  nginx:
    build: ./docker/nginx # Utilise le Dockerfile dans docker/nginx
    ports:
      - "8080:80" # On accède au site via http://localhost:8080
    volumes:
      - .:/var/www:delegated # Partage du code source pour les assets
    depends_on:
      - php

  # --- POSTGRESQL  ---
  database:
    image: postgres:16-alpine # Version stable et légère
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - db_data:/var/lib/postgresql/data # /data est OBLIGATOIRE
    ports:
      - "5432:5432"


volumes:
  db_data:
