services:
  database:
    image: postgres:18.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=le_44
      - POSTGRES_DB=le_44
    volumes:
      - db_data:/var/lib/postgresql:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp





volumes:
  db_data:





